"""fixed user_tickets table

Revision ID: 0d5438c846eb
Revises: cac048bef959
Create Date: 2025-02-18 11:40:38.059299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5438c846eb'
down_revision = 'cac048bef959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.drop_column('sale_start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_start_date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
