name: Deploy Frontend to Netlify

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.9.0"  

      - name: Install Dependencies
        run: |
          cd client
          npm install

      - name: Run Tests
        run: |
          cd client
          CI=false
          npm test  

      - name: Build Project (if tests pass)
        if: success()
        run: |
          cd client
          CI=false
          npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify (if build succeeds)
        if: success()
        run: |
          netlify deploy --dir=client/build --prod \
          --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} \
          --site=${{ secrets.NETLIFY_SITE_ID }}
